services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  springboot:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: springboot
    depends_on:
      - postgres
      - redis
    ports:
      - "${SPRINGBOOT_PORT}:${SPRINGBOOT_PORT}"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql:///${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${INSTANCE_CONNECTION_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      APP_S3_REGION: ${APP_S3_REGION}
      APP_S3_BUCKET: ${APP_S3_BUCKET}
      APP_CDN_DOMAIN: ${APP_CDN_DOMAIN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    env_file:
      - .env

#volume
volumes:
  postgres_data:
