apiVersion: v1
kind: Service
metadata:
  name: trippin-backend
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: trippin-backend
  ports:
    - port: 80
      targetPort: 8080
