apiVersion: apps/v1
kind: Deployment
metadata:
  name: trippin-backend
  namespace: default
  labels:
    app: trippin-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trippin-backend
  template:
    metadata:
      labels:
        app: trippin-backend
    spec:
      containers:
        - name: trippin-backend
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: trippin-db
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trippin-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trippin-db
                  key: password
